version: '3.8'
services:

  app:
    container_name: breeds-cats_api
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=breeds_cats
      - DB_HOST=database
      - DB_PORT=5433
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5433
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=breeds_cats
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5433
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: